// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripsLogApp.Models;

namespace TripsLogApp.Migrations
{
    [DbContext(typeof(TripDetailContext))]
    partial class TripDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TripsLogApp.Models.TripDetail", b =>
                {
                    b.Property<int>("TripDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Accomodations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstThingToDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondThingToDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThirdThingToDo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TripDetailID");

                    b.ToTable("TripDetails");

                    b.HasData(
                        new
                        {
                            TripDetailID = 1,
                            Accomodations = "the Galt House",
                            Destination = "Louisville",
                            Email = "Trip1@gmail.com",
                            EndDate = new DateTime(2009, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstThingToDo = "Go to the Derby",
                            PhoneNumber = "502-555-9999",
                            SecondThingToDo = "Go drink bourbon",
                            StartDate = new DateTime(2008, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThirdThingToDo = "Go eat Pizza"
                        },
                        new
                        {
                            TripDetailID = 2,
                            Accomodations = "An AirBnB",
                            Destination = "Gatlinburg",
                            Email = "Trip2@gmail.com",
                            EndDate = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstThingToDo = "Go to Cade's Cove",
                            PhoneNumber = "502-555-9999",
                            SecondThingToDo = "Go drink moonshine",
                            StartDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThirdThingToDo = "Go eat pancakes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
